### ISSUE TITLE
[Android] Token Lost if "don't keep activities" enabled

### ISSUE THREAD

**Issue by codeknox** [MaikuB/flutter_appauth#102]
I was assigned this bug to investigate, and my conclusion is that it only happens when the user has enabled "don't keep activities" on Android settings.

The flow of the app is like this:

* app started
* it detects no token available
* starts oAuth
* user autorizes
* app started (again)

the flow makes sense, so I'm not here to discuss that, but I really wish someone could give me an idea of how to go around this?

I'm even thinking about the possibility of telling the user that with "don't keep activities" on, our app does not work.

Or is there a way to store the retrieved code on disk (like shared preferences) so I can check when the app starts the second time?

Thank you all for any hints,
.CodeKnox

**Comment by MaikuB** [comment]
Yes your app will need to consider and be responsible for the storage of tokens as part of using OAuth 2.0,  regardless of which plugin you use for authentication. If you haven't read more about OAuth 2.0 then I would suggest reading more about it. For example in https://developers.google.com/identity/protocols/oauth2/native-app, you see it mentioned that token information needs to be kept in long lived storage so tokens can be used between multiple sessions of an app. 

Based on my understanding of what you've written as part of your application's flow, it sounds like this is missing and it doesn't check for existing tokens. This might include where an access token has expired so rather than restarting the auth process, you should be using the refresh token to get a new one.

**Comment by codeknox** [comment]
Hey there @MaikuB , thank you for taking the time to write this explanation.
I understand what you wrote and we do save te token and do refresh the token.

But this is happening before I even get the token.

Let me number the steps we do:

The flow of the app is like this:

1. app started
2. it detects no token available
3. starts oAuth
4. user autorizes
5. app started (again)

As you see on step 2, we do not have a token yet.
This makes the app start the oAuth authentication process (step 3).
Once user has authorized (step 4), control is returned to our app, but because of the "Don't keep activities', app is just restarted (step 5). As we have never received the token to begin with, this becomes step 1 and the flow restarts again.

For now, the only way I see around this is to actually hack into your source code and "save" the token, so I could check on the possible return to 1.

Hope this is clearer now?
.CodeKnox

**Comment by MaikuB** [comment]
Ah apologies, yes that's clearer now. Since you mentioned token storage I thought this was after the token was obtained. Does seem like you need to hack it. If you look on the repo for the Android SDK there is at least one open related issue https://github.com/openid/AppAuth-Android/issues/240

**Comment by MaikuB** [comment]
Closing as there's not much I can do about this

**Comment by aries-segue** [comment]
can we not fix it like how image_picker plugin has done? Its just a thought, I have not gone through the code in detail
https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android
