### ISSUE TITLE
Dart Native OAuth

### ISSUE THREAD

**Issue by MisterJimson** [MaikuB/flutter_appauth#136]
just curious if there is any desire to implement OAuth in dart as much as possible, and only using the native APIs for opening the browser window when needed.

This would make the library more portable for other Flutter platforms like Desktop and Web, and make it easier to contribute to and debug.

Just wanted to get thoughts.

**Comment by MaikuB** [comment]
I'm curious how that is much different from what is already happening already except that the process of opening the browser is handled by the native AppAuth SDKs.

Also the purpose of the plugin is to be wrapper for native AppAuth SDKs. There are already SDKs for other platforms so if you intend to contribute then so long as it's to wrap SDKs for other SDKs then PRs are welcome. In other words, if you're proposing to not use the AppAuth SDKs developed by the community then I've no plans do that

Some architectures will potentially already add an abstraction on top of the plugin so that implementations could be swapped out. That approach could be used so that different plugins are used based on the platform that the app is running on

**Comment by MisterJimson** [comment]
Understood, thanks for taking the time to reply.

I agree that the process would be very similar to how it is now, but doing the discovery within Dart would possibly be more performant (less/no method channels), and implementation between platforms would be more consistent (avoiding differences in implementation between iOS/Android/new platform).

But I completely understand that that may not be the direction this project is going. I mostly wanted to see if you or anyone had thoughts on this.

Feel free to close if you don’t think there is valuable discussion for this project here.

**Comment by MaikuB** [comment]
The discovery is done only when an authorisation request is made using the discovery url so it doesn't result in less calls via platform channels if the change were made. I've seen issues raised on the performance of web requests via Dart compared to using the native implementation as well.

Going to close this
