### ISSUE TITLE
Nullsafety version depends on 2.0 of _interface instead of 3.0 null safety version

### ISSUE THREAD

**Issue by JohnGalt1717** [MaikuB/flutter_appauth#188]
Please update so that everything is consistent.

**Comment by MaikuB** [comment]
Are you maintaining your own version of the plugin as I'm not sure how you're seeing this. The PR at https://github.com/MaikuB/flutter_appauth/pull/187 shows it's pointing to 3.0 null safety version. Same if you download it off pub at https://storage.googleapis.com/pub-packages/packages/flutter_appauth-1.0.0-nullsafety.0.tar.gz and extract the files out

**Comment by JohnGalt1717** [comment]
I think what's happening is that it's being blocked because of the plugin_platform_interface requiring >= 2.0.0 which most other stuff doesn't so I'm getting a false on this.  Can you expand it to >= 1.0.1 && < 3.0.0?

**Comment by MaikuB** [comment]
Ah i see first party plugins updated to that range your mentioned recently. I'll do so as well  but won't get to it until much later in the day since I work on this during spare time

**Comment by JohnGalt1717** [comment]
No problem at all.

**Comment by MaikuB** [comment]
Published a new version of `flutter_appauth_platform_interface`. It should still satisfy the constraints for `flutter_appauth` that running `flutter pub upgrade` should pull it down. As such, I haven't published a new version of `flutter_appauth`. Let me know if you still have issues with either of these

**Comment by JohnGalt1717** [comment]
@MaikuB Looks good.  One question though.

On AuthorizationTokenRequest clientid and redirectUrl are nullable.  I would have expected these to not be nullable like AuthorizationRequest and TokenRequest (since it's my understanding that AuthorizationTokeRequest is used to do code flow where you do an Authorization request and then a token request with the authorization_code and the code verifier. So in no case would these be nullable?

What am I missing?

**Comment by MaikuB** [comment]
I had some issues with making this non-nullable before as it was saying it needed to be initialised since those were defined in `CommonRequestDetails` that only gets extended. Just remembered though that I can apply the `late` keyword so that it can be non-nullable

**Comment by JohnGalt1717** [comment]
@MaikuB That would be excellent!  

Would love it if we could get in the web's processStartup requirement into the platform interface. There's no way to work around this and it would require special hacking for users of this to make it work eitherwise with bait and switches etc.

It's method signature is: Future<AuthorizationTokenResponse?> processStartup(AuthorizationTokenRequest);

ios, android, windows, mac, linux would all just do no-ops on these, but web requires it because of the redirect out and then come back and reload process that's required.

If we had that in the platform interface then I can do a pull request to put in the web code.

Thanks!

**Comment by JohnGalt1717** [comment]
@MaikuB That would be excellent!  

Would love it if we could get in the web's processStartup requirement into the platform interface. There's no way to work around this and it would require special hacking for users of this to make it work eitherwise with bait and switches etc.

It's method signature is: processStartup(AuthorizationTokenRequest)

**Comment by MaikuB** [comment]
From my understanding around the recommended approach null safety migration, any changes are best discussed and done after null safety goes to stable. It looks like null safety releases focus purely on migration with no new features added and I assume this is to help limit the scope of what needs to be tested.

One of the things I'm thinking about is whether or not it makes sense for this plugin to be extended to support other platforms. Whilst it helps to have everything handled by this plugin. It's original purpose and the reason why it's named the way it is was because it was a wrapper for the AppAuth SDKs. These SDKs are only available on a limited number of platforms. Extending this, potentially means considering having the plugin renamed.

Out of curiosity, is this an alternative GitHub account you're using or is it just coincidence that you share the same name as https://github.com/jhancock4d :)

**Comment by JohnGalt1717** [comment]
Personal account versus corporate one and damn window it picks to open has different profiles.

I'd encourage a single package that handles all platforms for openidconnect. This is the only solution right now other than using firebase which is not an option for many. (we have a prohibition in the company for using Firebase for anything but Android push notifications because of the Google making money of our corporate customers and GDPR implications of that.)

**Comment by MaikuB** [comment]
> Personal account versus corporate one and damn window it picks to open has different profiles.

Ah ok

> I'd encourage a single package that handles all platforms for openidconnect.

Yeah I know it'd make it a lot more easier for users. One option is this plugin endorses other plugins that implement support on other platforms. For example, Linux support is implemented in another plugin by another maintainer. The plugin that exposes the cross-platform facing API is able to redirect requests to it on Linux by endorsing the Linux implementation via the pubspec.yaml file. That was one of the things that federated plugins supported that as maintainers may know have the skills to implement support for all platforms. I haven't come across a scenarios (i.e. plugins) that tried to leverage this yet though...

**Comment by JohnGalt1717** [comment]
@MaikuB  Well that can be viable, but the problem with web is that it still needs the bait and switch to hide what's going on.  Maybe, web gets added and the desktops are separate or something? Although I can trivially add UWP when it's ready shortly... I'm happy to help maintain this especially on web and UWP. (I consider win32 as a pointless exercise but it could be added too, it would just have to use the device code flow)

**Comment by MaikuB** [comment]
To clarify, I was referring more to how it's not absolutely necessary for PRs to add support for other platforms to go to the repo but open to look at them. 

To follow up on the original issue though, it looks like the first-party Flutter plugins have all now changed the constraints for `plugin_platform_interface` to `^2.0.0` again to avoid 1.x being picked up since that isn't null safe. As such, I'll likely revert the change soon and looking more into it, I believe the original issue here was that other packages hadn't done the work to migrate to null safety. If so, I'd suggest opening an issue for the maintainers of those packages to look at migrating to null safety as `plugin_platform_interface` 2.0 is the null safety release

**Comment by MaikuB** [comment]
I pushed out a change to go back to `^2.0.0`. Looking to publish all of nnbd work as a stable closer to end of the month. Closing this now since first party plugins have changed to use `^2.0.0` too
