### ISSUE TITLE
[Android] Cannot callback app when browser is not Chrome, Firefox, Samsung browser

### ISSUE THREAD

**Issue by ghost** [MaikuB/flutter_appauth#207]
I try to login on Huawei device using Huawei browser. 
After inputing username & pass, try to callback app then I got 'Requested endpoint is forbbiden'
Reason: Appauth has just supported 3 browsers as Chrome, Firefox, Samsung browser on Android device.

**Comment by IonVillarreal** [comment]
I have the same problem in Huawei, sometimes I get an alert 'You want to open the application' when returning to the application in the authentication flow, sometimes it also does not come out 🤷‍♂️

**Comment by MaikuB** [comment]
This plugin is a wrapper for the native AppAuth SDKs so would be limited to whatever browsers the SDKs support. You would need to open a feature request to the appropriate SDK to support other browsers though it's possible that it doesn't support it because it's not technically possible to do so. Closing this as this isn't something the plugin can address
