### ISSUE TITLE
TokenRequest is not working with IdentityServer3 auth provider 

### ISSUE THREAD

**Issue by delllive** [MaikuB/flutter_appauth#208]
TokenRequest is not working with IdentityServer3 auth provider. It is  showing error invalid_grant. I checked all values are correct but still error comes.

**Comment by MaikuB** [comment]
The only thing I can say is you'd need to look into your issue further. The plugin makes use of SDKs that follow the OAuth 2.0 standard so as long as you've configured everything properly and your server follows the same standards then it should work. The error you're getting occurs due to an issue with the values being sent from the client/app. Furthermore, the app works on the IdentityServer4 demo server and I wouldn't there to be a change from IdentityServer3 to IdentityServer4 that leads to an error like this. Tracking issues specific to the service you're using would be something you need to look into yourself as well
