### ISSUE TITLE
[iOS] Cookies not kept after successfully login in browser/other SFSafariViewController/ASWebAuthenticationSession

### ISSUE THREAD

**Issue by AlexisDeslandes** [MaikuB/flutter_appauth#215]
Hello, 

after successfully login to my app using FlutterAppAuth.token method, i want to open a safari browser using eg : url_launcher.
The safari browser links to the same website as i connect to, so I'm expecting the website to not display a login page but directly the content i'm asking. I saw the parameter preferEphemeralSession but i'm not using it when I log i'm only using token() issuer, scopes, clientSecret and refreshToken additional parameters.

Any idea of what I did wrong ?

Thanks

**Comment by MaikuB** [comment]
You haven't done anything wrong and it would be to do with how the platform works. The iOS docs [here](https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service?language=objc) states that session cookies aren't shared with the browser and you can see a discussion [here](https://github.com/openid/AppAuth-iOS/issues/120) that Apple changed how iOS works with regards to sharing cookies before

**Comment by AlexisDeslandes** [comment]
Thanks for the info !

**Comment by durga-nannamsetty** [comment]
Any update on this? Because I have similar functionality in my app.

We are developing a Flutter app and need to integrate OAuth2. We also have existing web app that is OAuth2 enabled, and the user can open the web links from our (new) Flutter app.

We have decided to use “AppAuth” to implement the authentication part mainly to support SSO between the flutter app + the web app that we open inside the mobile app in few screens. And we are using “url_launcher” package to open the web app links.

We can login inside the app using “AppAuth” package. No issues in this.

However, when I login to the mobile app, and try to open the web app link using “url_launcher” package the web app prompts for the login credentials. But our expectation is that it should not prompt for login again because user already logged in for the same OAuth2 configuration.

I could able to resolve this in **android** by using ChromeSafariBrowser from "flutter_inappwebview" package.

But I would like to get some understanding on this problem in iOS.

@AlexisDeslandes did you found any solution for iOS?

**Comment by AlexisDeslandes** [comment]
No I didn't find solutions sorry ...
