### ISSUE TITLE
Refresh token issue

### ISSUE THREAD

**Issue by stephengibson83** [MaikuB/flutter_appauth#226]
I found this library after following the Auth0 guide: https://auth0.com/blog/get-started-with-flutter-authentication/

My flutter application has null safety enabled so I'm using version 1.1.0 of flutter_appauth.

When using a refresh token in FlutterAppAuth.token() I get the following error:

> flutter: error on refresh token: PlatformException(token_failed, Failed to get token: invalid_grant: Unknown or invalid refresh token., null, null) - stack: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
flutter: #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
flutter: <asynchronous suspension>
flutter: #2      MethodChannelFlutterAppAuth.token (package:flutter_appauth_platform_interface/src/method_channel_flutter_appauth.dart:53:9)
flutter: <asynchronous suspension>

When using version 0.9.1 of flutter_appauth I do not get this issue.

Also, in Auth0 when "Refresh Token Rotation" is enabled the refresh token is longer (e.g. "v1.Mje5BfzlZgH2rMthhzSMvKPcg9gd_zPOnEqAKOiekd7VKcRipganI62QjwyHVUsrQKYepp_VLsg6TePsrABOkxc"). But when disabled, the token is shorter (e.g. "IZ1GghE_E9R2j5TZlfzBW0t7QhUpTgpA-CUWk1d2K23VM").  Again, the longer token is fine when used with version 0.9.1.

**Comment by JohnEmerson1406** [comment]
I follow the Auth0 guide and I had the same error: PlatformException (PlatformException(token_failed, Concurrent operations detected: token, token, null, null))

**Comment by MaikuB** [comment]
The major difference between the two versions you mentioned is around the plugin being migrated to null safety. Furthermore, the error you would see is what gets returned by Auth0 and only happens when an application is sending an invalid refresh token. If there was an issue with the plugin itself on this then this should happen regardless of which IdP is used such that it would also happen with the example app and there'd more reports on this issue. I've also used 1.10 with Auth0 with code that has been migrated to null safety and haven't seen any errors.

As such the only guidance I can give is to check your application and Auth0 configuration. Perhaps you haven't migrated your code to null safety properly to have additional checks to prevent a null refresh token being passed.
