### ISSUE TITLE
token refresh issue 

### ISSUE THREAD

**Issue by miduch** [MaikuB/flutter_appauth#24]
Hi, 

using appAuth.authorizeAndExchangeCode() i'm successfully getting token but authorizationAdditionalParameters is empty in this case, later when i want to refresh token using appAuth.token() i need to provide authorizationCode which i didn't receive earlier. 

Shouldn't you pass AuthorizationResponse instead of null in following 
 
/.pub-cache/hosted/pub.dartlang.org/flutter_appauth-0.2.1+1/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java

```
            public void onTokenRequestCompleted(
                    TokenResponse resp, AuthorizationException ex) {
                if (resp != null) {
                    Map<String, Object> responseMap = tokenResponseToMap(resp, null);
                    finishWithSuccess(responseMap);
                } else {
                    finishWithTokenError(ex);
                }
            }


```

Thanks!

**Comment by MaikuB** [comment]
There's no AuthorizationResponse to pass at that stage that's why it's null. Not sure why you're trying to use an authorization code to do a refresh. Authorization code is mainly used when you're trying to get the initial access token and refresh token so it's purpose isn't really for refreshing. If you want to refresh your token, you generally do this by passing a refresh token. There's an example app in the repo to demonstrate this as well. If you really want the authorization code then you call `authorize(...)` instead. The example app also covers this

**Comment by miduch** [comment]
Isn’t following mentioning auth code for token refresh? 

![F383AF2B-1B72-4F4A-98D3-C7FB11E70FAC](https://user-images.githubusercontent.com/22243296/58571328-2e6f2880-8242-11e9-96b5-84eb1d71c64c.jpeg)

**Comment by MaikuB** [comment]
ah my bad, need to clean up that bit in the readme. if you look at the example app, authorization code isn't actually needed so if you had passed in null i would expect the code to execute without any errors though not sure if you have tried that. will update the readme soon

**Comment by MaikuB** [comment]
readme should be fixed now. thanks for picking that up
