### ISSUE TITLE
Errors when targeting Android SDK 30

### ISSUE THREAD

**Issue by kennethj** [MaikuB/flutter_appauth#241]
Targeting Android SDK 30 breaks the authentication features when using `net.openid:appauth` versions below 0.8.0.

Update the dependency to a newer version:
https://github.com/MaikuB/flutter_appauth/blob/master/flutter_appauth/android/build.gradle#L37

https://github.com/openid/AppAuth-Android/releases

This looks like it may be an issue pretty soon. https://developer.android.com/distribute/best-practices/develop/target-sdk#pre11
 
> Starting in November 2021, app updates will be required to target API level 30 or above

**Comment by MaikuB** [comment]
There's an open PR https://github.com/MaikuB/flutter_appauth/pull/216 which an associated prerelease so please use this.It's only in pre-release due to the end session functionality so you can have your app reference that as it's not functionality you would've used before. This is also helps with identifying any issues

**Comment by MaikuB** [comment]
Actually i'll do a minor version to bump the versions as more feedback may needed on the end session pre-release
