### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable

### ISSUE THREAD

**Issue by cristechvify** [MaikuB/flutter_appauth#242]
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
Is there any way to fix this issue on iOS? On android virtual machine still running normally

**Comment by MaikuB** [comment]
There haven't been any other reports on this and this is an error that would be returned from the server side. Therefore, this would be specific to your cirumstances that you'd need to investigate further.

**Comment by sebastianspross** [comment]
@cristechvify have you solved the issue or found the root cause?

I am running into the same while trying the request token for the first tie. Android is running with AAD B2C without any problems and iOS is returning "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." when calling

```
result = await _appAuth.authorizeAndExchangeCode(
  AuthorizationTokenRequest(
    _clientId,
    _redirectUrl,
    discoveryUrl: _discoveryUrl,
    scopes: _scopes,
  ),
);
```

**Comment by sebastianspross** [comment]
In this [issue ](https://github.com/openid/AppAuth-iOS/issues/475)I found the solution. This issue is only with the iOS and not Android library.

When you are using the discoveryUrl or specific endpoints the autorize endpoint should look like this:

```
https://<name>.b2clogin.com/<name>.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_flutter
```

But in iOS the query param is in the AppAuth library for some reason cut. You need to add the `p=b2c_1_flutter` by `additionalParameters`.


```
Map<String,String> additionalParams = {"p":"b2c_1_flutter"};
      // show that we can also explicitly specify the endpoints rather than getting from the details from the discovery document
      final AuthorizationTokenResponse? result =
          await _appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          _clientId,
          _redirectUrl,
          serviceConfiguration: _serviceConfiguration,
          scopes: _scopes,
          preferEphemeralSession: preferEphemeralSession,
          additionalParameters: additionalParams,
        ),
);
```


@MaikuB have you experienced similar issues? I am wondering if the flutter_appauth on iOS ever worked with AAD B2C? Probably we should add something to the docu

**Comment by MaikuB** [comment]
No I haven't and I don't have access to an Azure B2C tenant to test anymore but it has definitely worked in my experience and I've seen articles going through how to do so too. You can specify the endpoints directly if you have issues with the discovery URL like you mentioned. I should also point out that Microsoft's own documentation does allow for the policy to be in the path as opposed to be in  query string

**Comment by bryanCancelWT** [comment]
I'm leaving this here for anyone that ends up arriving here
I did what @MaikuB mentioned and included the policy in the url as follows
https://{name}.b2clogin.com/{name}.onmicrosoft.com/{policy}/oauth2/v2.0/{authorize -or- token -or- logout and discovery might work here too but I haven't test them yet}
name == tenant_name

**Comment by dupuisdavid** [comment]
Hello.

@sebastianspross, I'm facing the same issue.
I tried your solution: removing the query string from the authorizationEndpoint in AuthorizationServiceConfiguration and adding it as an additional parameter. Result: when the auth dialog appears, I get this error message: "Safari cannot open the page because the address is invalid".
