### ISSUE TITLE
Using biometrics hangs in iOS

### ISSUE THREAD

**Issue by poqueque** [MaikuB/flutter_appauth#247]
I'm using AppAuth with login/password and fingerprint. It's all working fine in Android, but for iOS, after successfully enter the fingerprint, the "Sign In" dialog remains on screen. The method AuthorizeAndExchangeCode returns ok and the login is processed successfully, but for some reason the "Sign In" dialog does not dissapear. The device does not react to button clicks so the only solution is to restart it.

**Comment by MaikuB** [comment]
I'm not familiar with how you have biometrics working on iOS and with your IdP (identity provider). If I understood you correctly though, the issue is that the redirect isn't happening. If so, then that generally's a sign that you haven't configured the redirect URL and/or scheme properly within your app or as part of the configuration on the IdP side
