### ISSUE TITLE
How to end session without open external browser ?

### ISSUE THREAD

**Issue by postflow** [MaikuB/flutter_appauth#279]
My method for logout:
```
endIdentitySession() async {
    await appAuth.endSession(EndSessionRequest(
         idTokenHint: idToken,
         postLogoutRedirectUrl: AUTH0_REDIRECT_URI,

        serviceConfiguration: AuthorizationServiceConfiguration(
            authorizationEndpoint: 'https://$AUTH0_DOMAIN/connect/authorize',
            endSessionEndpoint: 'https://$AUTH0_DOMAIN/connect/endsession',
            tokenEndpoint: 'https://$AUTH0_DOMAIN/connect/token')
    ));
  }
```
but when i call this method, opening browser (chrome custom tabs). How to silent (without open external browser) logout user ?

**Comment by MaikuB** [comment]
It isn't possible and opening the browser is the expected behaviour as this is what allows the user to be signed out from the browser, which is a similar to how signing in works.

Sidenote: I noticed your code mentions Auth0. From what I've seen, they don't follow the [same standard](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) in providing an end session endpoint
