### ISSUE TITLE
Does not work for GitHub on iOS.

### ISSUE THREAD

**Issue by NamanShergill** [MaikuB/flutter_appauth#330]
Because of the following issue: https://github.com/openid/AppAuth-iOS/pull/206#issuecomment-394048448

Any ideas?

**Comment by MaikuB** [comment]
Not familiar with the topic at hand but as you would've already seen, this plugin makes use of AppAuth Android and iOS SDKs. You'll need to look into your own solution if the native SDKs don't support it. The post you linked to already mentions a potential solution which you would need to do yourself for your own purposes

**Comment by NamanShergill** [comment]
I tried forking the native sdk, making the change,and your repository to depend on it, but it doesn't seem like I can add a local path for dependencies in the podfile.

I am not as well versed with how iOS side of the flutter plugin development works so I'm not sure if I missed something? How can I use the modified native SDK with your library as a local dependency?

**Comment by MaikuB** [comment]
What you pointed out is more to do with iOS development in general than Flutter plugin development. This is something you'd need to look into, I'm not an iOS developer myself and picked up the bare minimum to work on libraries such as this and is done on spare time. Sounds odd that you want to reference a local path as since you forked, it should be reference a fork via Git. There are likely ways to do this but not something I've worked with

**Comment by NamanShergill** [comment]
I actually added it as a submodule to my project lol so not really a fork, but I guess a fork is the way to go. Thank you for your help!

**Comment by NamanShergill** [comment]
If anyone stumbles on this issue looking for the best way to fix it, add the following line to your project's `iOS/Podfile`

```
pod 'AppAuth', :git => 'https://github.com/NamanShergill/AppAuth-iOS.git'
```

Or link to your own fork with the fix.

This will override the sdk being used in the `flutter_appauth` library.
