### ISSUE TITLE
Token response expected?

### ISSUE THREAD

**Issue by lukepighetti** [MaikuB/flutter_appauth#46]
Hi there, I'm sure this is not specific to `flutter_appauth` but I'm not sure where else to ask this question. So my apologies for doing this as an issue.

I have my custom scheme setup and I've got `flutter_appauth` sending a `code` to my server which has a valid token ready to respond with.

I've tried responding with `my-app-scheme:/instagram-auth?token=foo` and the browser window closes as expected but nothing returns from `AppAuth.authorizeAndExchangeCode`

So my question is what should I be returning to catch the attention of App Auth and complete the token exchange? 

It seems like `flutter_app_auth` would need to know the scheme to listen on?

I found this documentation but it is not clear on what needs to be returned and I don't see any guidelines for AppAuth itself

https://tools.ietf.org/html/rfc8252#section-7

**Comment by MaikuB** [comment]
When you say

> I have my custom scheme setup and I've got flutter_appauth sending a code to my server which has a valid token ready to respond with.

does that mean you've let the plugin handle getting the authorisation code as well (which would be done if you've called `authorizeAndExchangeCode`)?

With regards to specifying the scheme, there are a few parts that require this to be configured correctly

- the scheme should be part of the redirect url
- on Android, the scheme should be in your app's `build.gradle` file
- on iOS, the scheme is specified in your app's `Info.plist` file

Perhaps the last two parts are what you're missing. They're mentioned in the readme and you can look at the example app to see the relevant sections ([Android](https://github.com/MaikuB/flutter_appauth/blob/407b89bbe53b9c8bbff264f3fdea9390bace166f/example/android/app/build.gradle#L44) and [iOS](https://github.com/MaikuB/flutter_appauth/blob/407b89bbe53b9c8bbff264f3fdea9390bace166f/example/ios/Runner/Info.plist#L12))

**Comment by lukepighetti** [comment]
Sorry I will try to be more clear


```dart
_appAuth.authorizeAndExchangeCode(
  AuthorizationTokenRequest(
    "3acdbaab72a84abe8d522c11b27f176b",
    "https://us-central1-skatex-8d802.cloudfunctions.net/authInstagram", /// My server endpoint to redirect to
    serviceConfiguration: AuthorizationServiceConfiguration(
      "https://api.instagram.com/oauth/authorize/", /// Instagram auth 
      "https://api.instagram.com/oauth/access_token", /// Instagram token endpoint, i only use this on the server though?
    ),
  ),
```

Mobile app calls authorizeAndExchangeCode
Endpoint is hit, code is sent
Endpoint takes code, sends it to "https://api.instagram.com/oauth/access_token", gets token

Now the endpoint has the token, and the mobile app has the browser window waiting for a response. Not sure what happens next and how the response should be formatted etc.

**Comment by lukepighetti** [comment]
I will note that instagram requires https redirect uris, which is why i tried to handle the code/token on my server.

**Comment by MaikuB** [comment]
Ah ok it's because your a https redirect but the apps are configured to only handle custom schemes. If the scheme in the browser matches what's configured in your apps then it's able to process the URLs to extract out the token. This isn't the case right now, which is why it's not working. You might want to try to see if it's possible configure the plugin to use https as the scheme. It's not something I've tried so don't know if it'll work

**Comment by lukepighetti** [comment]
Hang on, I've got an idea to split up with a `.token()` and `.authorize()`, i'll fiddle

**Comment by MaikuB** [comment]
Might be that you wrote your reply before seeing my last one but technically AppAuth doesn't actually listen for the redirect URLs, it simply issues web requests. It's your app that handles the redirects but it's via the scheme. Generally, handling https redirects requires more configuration on your web server to verify that your own the domain and that the app can be trusted to handle redirects from that domain. Refer to https://developer.android.com/training/app-links and https://developer.apple.com/ios/universal-links/

**Comment by lukepighetti** [comment]
I am familiar with handling app links so maybe some clarification would be helpful. Are you saying that AppAuth does not handle receiving a token? I thought AppAuth and therefore `flutter_app_auth` would receive a token.

**Comment by lukepighetti** [comment]
I assumed I could just redirect to the uri scheme with the appropriate headers (I don't know what they are, I don't know what AppAuth is looking for) and that'd be it

**Comment by MaikuB** [comment]
> Are you saying that AppAuth does not handle receiving a token?

It will handle receiving the token provided you need to have configured the app scheme that matches what's used in the redirect url. Right now they don't match so it doesn't work. This is why I was saying "You might want to try to see if it's possible configure the plugin to use https as the scheme". Though what I should've written is to configure your app to use https as the scheme not the plugin.

> Surely AppAuth is waiting for a redirect to a specific scheme to trigger closing the web browser and completing the request?

Yes but the scheme you've configured your app to look out for doesn't match what it's in the redirect url. The browser ends up redirecting to `https://us-central1-skatex-8d802.cloudfunctions.net/authInstagram` but since the scheme doesn't match, it doesn't no it should process the URL to let AppAuth extract the token to return a result back to your app (i.e. to let the future complete)

You could try seeing if configuring for https redirect in the readme of the AppAuth Android SDK works https://github.com/openid/AppAuth-Android. I assume for iOS it's just the same process for handling universal links. Note that I've never tried this plugin with https redirects

**Comment by MaikuB** [comment]
One other option that may work if https redirect with this plugin doesn't work is to have requests to `https://us-central1-skatex-8d802.cloudfunctions.net/authInstagram` redirect to a url with `appauth-f397e03b-c667-4cd9-950e-9c66b3595754` as the scheme whilst passing the query string parameters. since the tokens generally get attached to the URL as query string parameters

**Comment by MaikuB** [comment]
Hmm I just saw this thread that also suggests that the response from Instagram's API isn't OAuth2 compliant https://github.com/openid/AppAuth-Android/issues/233. It's an old thread so not sure if that's still the case. If it is then you may need to look at using another plugin for handling authentication

**Comment by lukepighetti** [comment]
>One other option that may work if https redirect with this plugin doesn't work is to have requests to https://us-central1-skatex-8d802.cloudfunctions.net/authInstagram redirect to a url with appauth-f397e03b-c667-4cd9-950e-9c66b3595754 as the scheme whilst passing the query string parameters. since the tokens generally get attached to the URL as query string parameters

That's what I've been trying to communicate to you but I'm not doing a good job. The problem is that I don't know what AppAuth is looking for to close the browser and continue on the process. Does that make sense? I'm trying hard to be clear but my terminology might be off.

**Comment by lukepighetti** [comment]
What's interesting is even if I supply my own scheme listener (ie `uri_links`) it won't hear any redirects to my schemes from within the AppAuth browser. I have to exit the browser, open safari, and paste in a link for it to actually make it to my app. (Slightly unrelated?)

**Comment by MaikuB** [comment]
> I can redirect to appauth-f397e03b-c667-4cd9-950e-9c66b3595754:/whatever but I have no idea what it's looking for to complete the process. I 

If you have that setup, since the scheme matches, the app would be able to process the URL. AppAuth would then see if it matches the redirect URL. If it does then it extracts out the token etc.  At least that's my understanding of it. Would most likely need to look at the code to figure out the inner workings of that process though pretty confident that should be how it works based on my experience with app links

**Comment by MaikuB** [comment]
As I don't have experience with using the plugin with Instagram's API and haven't tried it out with https redirect, if you continue to run into problems then perhaps try using https://pub.dev/packages/simple_auth

**Comment by lukepighetti** [comment]
I appreciate the help. To be clear, I'm not doing the entire instagram auth system. I'm using the instagram token on the server to issue my own firebase token. The key is to pass the token to AppAuth and close the browser window but I cannot figure out how.

**Comment by MaikuB** [comment]
Afraid I don't know how to help in that case since you have your own logic in there beyond what I've mentioned above i.e. you likely need to make the browser redirect to the URL that matches the redirect url you've specified with the query string parameters as well. Probably need to swap out the access token with the firebase one your own server issues.

**Comment by lukepighetti** [comment]
I think that's the problem. Instagram needs the redirect url to be `https://myserver.com/foo` and AppAuth is trying to listen for action on `https://myserver.com/foo` which wouldn't occur with a basic scheme like `com.example.myscheme:/`

I posted this up just in case you find it of interest. Thanks again for the help!!

https://stackoverflow.com/questions/58134664/what-response-is-appauth-looking-for-to-close-the-browser-window-and-complete-re
