### ISSUE TITLE
Algumas Duvidas

### ISSUE THREAD

**Issue by dieos2** [MaikuB/flutter_appauth#50]
Eu tenho um identity server 3 rodando (já tem um tempo) e fiz o app logar com nesse serviço.
Só que eu não tenho uma api que buscar usuário por token, como eu pego o Sub de quem logou para tratar na api que já tenho? 
Obrigado.

**Comment by MaikuB** [comment]
I'd kindly ask that you post in English as that's the primary language used in Github. Otherwise look for an online community (e.g. slack workspace) that can speak the same. This would help avoid issues with inaccuracies in automated translation and provides a more sustainable way for maintainers to provide help.

Right now all I can get is that you're using identity server 3 and seem to be asking questions related to it. This doesn't look like it's an issue with the plugin. Please note that the example with identify server, is just that (i.e. an example). If you need to get other data from other endpoints then that is something you need to figure out.
