### ISSUE TITLE
appauth.authorizeAndExchangeCode crashes app

### ISSUE THREAD

**Issue by WJayesh** [MaikuB/flutter_appauth#61]
I am using Azure AD B2C for the project and followed Nick Randolph's video by NDC Conferences
I've followed the documentation to write the following code:
```
FlutterAppAuth _appauth = FlutterAppAuth();
    AuthorizationTokenResponse result;
    try{
    result = await _appauth.authorizeAndExchangeCode(
      AuthorizationTokenRequest(clientId, redirectURL,
          discoveryUrl: discoveryURL, scopes: scopes),
    );
    }
    catch(e){
      print(e.toString());
    }
```
### **Problem**
The app crashes just as authorizeAndExchangeCode is invoked. No exceptions were raised.

**What I know**
There should not be any problem with the client id, redirect url and discovery url. I had initial concerns about the discovery url but I have discovered that having a wrong url raised an exception.  My discovery url : `https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`

What am I missing?

**Comment by MaikuB** [comment]
The Azure B2C discovery endpoints I've seen don't look like the one you've been using. They're more like the ones shown in the Microsoft's docs [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc#validate-the-id-token) and the ones in their native [iOS](https://github.com/Azure-Samples/active-directory-b2c-ios-native-appauth) and [Android](https://github.com/Azure-Samples/active-directory-b2c-android-native-appauth) samples that use AppAuth

**Comment by WJayesh** [comment]
Thanks for the fast response. I will admit I am confused with the endpoints. I used this [site ](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc)to get an idea of the URL I was using. 
I will check with the ones you've listed and get back

**Comment by MaikuB** [comment]
The link you sent is for Azure AD, which is different from Azure B2C. Should using the discovery endpoints not work for you, you can explicitly specify the endpoints. I recall having issues with the discovery ones in the past but that may have been because Microsoft's documentation and samples were inconsistent with the format of the URL to use at the time. Not sure if it's been addressed now

**Comment by WJayesh** [comment]
Ah, thanks for pointing that out; makes much more sense now. I will update once I try the new endpoints. Thanks!

**Comment by WJayesh** [comment]
I changed the discovery URL and it starts throwing this error : `PlatformException(discovery_failed, Error retrieving discovery document: [error: null, description: Network error]` . 
I have tried using  "issuer" attribute instead. Same exception. I have a good network connection. What does this exception mean? Thanks!

**Comment by MaikuB** [comment]
You'll likely need to dig through the native AppAuth SDKs to find out what exactly might cause that. Have you actually checked the discovery URL is valid though? Note what I said above that when I tried this before that some of the listed formats for the discovery URL actually had problems when used. You can try to explicitly specifying the token endpoint etc as there are standard conventions where they are located

**Comment by MaikuB** [comment]
You mentioned you followed Nick's videos but have you checked his [blog post](https://nicksnettravels.builttoroam.com/connecting-flutter-to-azure-ms-ignite/)? Perhaps your URL isn't correct or you have a configuration issue that you need to resolve

**Comment by WJayesh** [comment]
> You mentioned you followed Nick's videos but have you checked his blog post? Perhaps your URL isn't correct or you have a configuration issue that you need to resolve

Thank you 🙇  for this! I feel there might be things I have left out. I will verify and update

**Comment by WJayesh** [comment]
I got the flow working! Turns out I had a typo in my discovery URL. Thank you so much for helping out ❤️   
I'll close this issue; however I have a small probem - after login, the AuthorizationResponse object has a null access token field. I need the access token for my graph api calls. Thanks!

**Comment by jay-web** [comment]
Hi MaikuB, I have auth and token endpoint, so I implemented appAuth.authorizeAndExchangeCode(). Which work fine on android. But in IOS, app crashed with the error- **Assertion failure in  OIDScopeUtilities scopesWithArray:] and terminating app due to NSInternalInconsistencyException. reason: found illegal character in scope string.** 
I am searching on stackoverful on this error since last one week. But not helpful. Any guidance will be really appreciate. Thanks in advance.

**Comment by MaikuB** [comment]
I don't have any. The error itself seems to hint at the issue that you should be looking at (scope)

**Comment by jay-web** [comment]
Thanks for the response. you were right,  by mistake I was sending space character extra in scope parameter. Now it's not crashing but after entering the username & password, it's not getting back to the app. As per your documentation, I implemented redirect URL in info.plist file and build.gradle. So it's working in the android section. but not in IOS.  this is my custom redirect URL ( changing character due to security reasons ) 
**com.adcde://ext.app.45454.fdfdf.dfd.mobile**
this is working in android . please suggest

**Comment by MaikuB** [comment]
As per documentation, it's the custom scheme that goes into the info.plist not the redirect url as you are saying. If you still have issues I suggest you use places like stack overflow

**Comment by jay-web** [comment]
ok, thank you for your help !!!
