### ISSUE TITLE
Can't get token

### ISSUE THREAD

**Issue by WuRendong** [MaikuB/flutter_appauth#67]
Add following code snippet according to example.

```java 
 final AuthorizationTokenResponse result =
                    await appAuth.authorizeAndExchangeCode(
                  AuthorizationTokenRequest
                    ("xxxxxx",
                      "xxxx",
                      serviceConfiguration: _serviceConfiguration,
                      scopes: _scopes,
                    ),
                );

```
it seems work according to the UI flow, UI already show the redirect url screen, however,  result is still null.

**Comment by MaikuB** [comment]
I'm not sure why your message says to add that snippet to the example when the example already has code like this and works. The info you've probably isn't enough to go on and the example app in this repo demonstrates that it works. I suggest you take a look at the debugging output in case there are errors that you've missed.

The info you've provided doesn't indicate that an issue actually exists. If there is one, please look at forking the repo and update the example app with code that can reproduce the problem

**Comment by WuRendong** [comment]
Hi Michael,

Sorry to make you confused, I have detail parameters to handle oauth 2 process, and UI flows is just like following screenshot. [
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-07 at 09 24 06](https://user-images.githubusercontent.com/30660508/71860977-a209da00-312f-11ea-8e99-56e900fe3e90.png)
](url)  
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-06 at 17 49 30](https://user-images.githubusercontent.com/30660508/71861002-b948c780-312f-11ea-9c0f-eaeb87b724c7.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-07 at 09 32 54](https://user-images.githubusercontent.com/30660508/71861295-d336da00-3130-11ea-9273-ba0b92d5e90e.png)

**Comment by MaikuB** [comment]
Thanks but as per my previous response, the information you've provided doesn't help identify if there's really an issue. Unless you can do something like fork the repo so that the example app can be used to reproduce the issue then I can't help. It may be possible you've not configured everything that's needed or for some reason the service you're using (Unsplash) isn't compatible for some reason. The code is open source so you can debug to find the issue. There are many services out there that require auth that it's not sustainable for me to check every case where there's a potential issue.

**Comment by WuRendong** [comment]
close this issue, missing secret.
